let identifier = 0;

const teachtruth = [
  {
    id: identifier++,
    title: `Faithful Servants`,
    content: `Learn about those who served Jehovah faithfully with endurance and trust.\n\n1. Who was the first faithful servant mentioned in Genesis?\n\n2. What did Noah do to show his faith in Jehovah?\n\n3. How long did Noah take to build the ark?\n\n4. What did Jehovah tell Abraham to do with his son Isaac?\n\n5. How did Abraham show his faith in Jehovah?\n\n6. Who was Abraham’s wife?\n\n7. What promise did Jehovah make to Abraham about his offspring?\n\n8. Who was the mother of Joseph?\n\n9. How did Joseph remain faithful despite being sold into slavery?\n\n10. What position did Joseph eventually hold in Egypt?\n\n11. Who led the Israelites out of Egypt?\n\n12. How did Moses show faith when facing Pharaoh?\n\n13. What did Jehovah give Moses on Mount Sinai?\n\n14. Who was Moses’ brother?\n\n15. How did Aaron support Moses in serving Jehovah?\n\n16. Who was the first king of Israel to be called a man after Jehovah’s own heart?\n\n17. How did David show faith when facing Goliath?\n\n18. What did David use to defeat Goliath?\n\n19. Who was David’s best friend?\n\n20. How did Jonathan show loyalty to David?`,
    answers: `1. Noah, 2. Built an ark as Jehovah commanded, 3. About 50-60 years, 4. Offer him as a sacrifice, 5. Obeyed Jehovah’s command without hesitation, 6. Sarah, 7. His offspring would be as numerous as the stars, 8. Rachel, 9. Refused to sin with Potiphar’s wife, 10. Second-in-command to Pharaoh, 11. Moses, 12. Trusted Jehovah to send the plagues, 13. The Ten Commandments, 14. Aaron, 15. Spoke for Moses and served as high priest, 16. David, 17. Trusted Jehovah to deliver him, 18. A sling and a stone, 19. Jonathan, 20. Protected David from Saul`,
    references: `Genesis; Hebrews 11`
  },
  {
    id: identifier++,
    title: `The 12 Disciples`,
    content: `Explore the lives of Jesus’ 12 disciples, who left everything to follow him.\n\n1. Who were the first two disciples Jesus called?\n\n2. What were Simon Peter and Andrew doing when Jesus called them?\n\n3. Who was the brother of Simon Peter?\n\n4. What did Jesus rename Simon?\n\n5. Who were the sons of Zebedee?\n\n6. What nickname did Jesus give James and John?\n\n7. Which disciple was a tax collector before following Jesus?\n\n8. What did Matthew do after Jesus called him?\n\n9. Which disciple is often called “the Doubter”?\n\n10. What did Thomas say after seeing the resurrected Jesus?\n\n11. Who betrayed Jesus for 30 pieces of silver?\n\n12. What did Judas Iscariot do after betraying Jesus?\n\n13. Who replaced Judas as an apostle?\n\n14. Which disciple was known as the one “whom Jesus loved”?\n\n15. What did John do at the Last Supper?\n\n16. Which disciple denied Jesus three times?\n\n17. What happened to Peter after he denied Jesus?\n\n18. Which disciple was also called Nathanael?\n\n19. What did Philip do after meeting Jesus?\n\n20. Which disciple was known as “the Zealot”?`,
    answers: `1. Simon Peter and Andrew, 2. Fishing, 3. Andrew, 4. Peter, 5. James and John, 6. Sons of Thunder, 7. Matthew, 8. Left his tax office and followed Jesus, 9. Thomas, 10. “My Lord and my God!”, 11. Judas Iscariot, 12. Hanged himself, 13. Matthias, 14. John, 15. Leaned on Jesus’ chest, 16. Peter, 17. He wept bitterly, 18. Bartholomew, 19. Brought Nathanael to Jesus, 20. Simon`,
    references: `Matthew 4:18-22; John 20:24-29; Acts 1:26`
  },
  {
    id: identifier++,
    title: `Restored Pure Worship`,
    content: `Discover how these characters helped restore pure worship to Jehovah.\n\n1. Who led the Jews back to Jerusalem to rebuild the temple?\n\n2. What role did Ezra have in Jerusalem?\n\n3. Who was the governor that worked with Ezra?\n\n4. What did Nehemiah rebuild in Jerusalem?\n\n5. How long did it take Nehemiah to rebuild the wall?\n\n6. Who opposed Nehemiah’s work?\n\n7. What did Ezra do to promote pure worship?\n\n8. Which prophet encouraged the rebuilding of the temple?\n\n9. What did Haggai prophesy about the temple?\n\n10. Who was the high priest during the temple’s rebuilding?\n\n11. What did Zerubbabel do for pure worship?\n\n12. Which Persian king allowed the Jews to return to Jerusalem?\n\n13. What decree did Cyrus issue?\n\n14. Who was the prophetess that helped during this time?\n\n15. What did Huldah prophesy about Josiah?\n\n16. Who found the book of the Law during Josiah’s reign?\n\n17. What did Josiah do after hearing the Law?\n\n18. Which king removed idolatry from Judah?\n\n19. What festival did Josiah reinstate?\n\n20. How did the people respond to Josiah’s reforms?`,
    answers: `1. Ezra, 2. Priest and scribe, 3. Nehemiah, 4. The city wall, 5. 52 days, 6. Sanballat and Tobiah, 7. Taught the Law to the people, 8. Haggai, 9. It would be filled with glory, 10. Joshua, 11. Led the people to rebuild the temple, 12. Cyrus, 13. To rebuild the temple in Jerusalem, 14. Huldah, 15. Judgment on Judah but peace for Josiah, 16. Hilkiah, 17. Removed idolatry and celebrated the Passover, 18. Josiah, 19. The Passover, 20. They obeyed the Law`,
    references: `Ezra; Nehemiah; 2 Chronicles 34`
  },
  {
    id: identifier++,
    title: `Bible Writers`,
    content: `Learn about the men Jehovah used to write His inspired Word.\n\n1. Who wrote the first five books of the Bible?\n\n2. What did Moses write about in Genesis?\n\n3. Which king wrote most of the Proverbs?\n\n4. What did Solomon ask Jehovah for?\n\n5. Who wrote the book of Isaiah?\n\n6. What major prophecy did Isaiah record about the Messiah?\n\n7. Which prophet wrote the book of Jeremiah?\n\n8. What did Jeremiah prophesy about Jerusalem?\n\n9. Who wrote the book of Daniel?\n\n10. What vision did Daniel have about the last days?\n\n11. Which disciple wrote the Gospel of Matthew?\n\n12. What was Matthew’s occupation before following Jesus?\n\n13. Who wrote the Gospel of Luke?\n\n14. What was Luke’s profession?\n\n15. Which apostle wrote the Gospel of John?\n\n16. What did John emphasize in his Gospel?\n\n17. Who wrote most of the Christian Greek Scriptures’ letters?\n\n18. What was Paul’s background before becoming a Christian?\n\n19. Which epistle did Paul write to encourage endurance?\n\n20. What did Paul say about the scriptures in 2 Timothy?`,
    answers: `1. Moses, 2. Creation and early human history, 3. Solomon, 4. Wisdom, 5. Isaiah, 6. The Messiah would be a suffering servant, 7. Jeremiah, 8. Its destruction by Babylon, 9. Daniel, 10. The march of world powers, 11. Matthew, 12. Tax collector, 13. Luke, 14. Physician, 15. John, 16. Jesus as the Son of God, 17. Paul, 18. A Pharisee and persecutor of Christians, 19. Hebrews, 20. They are inspired and beneficial for teaching`,
    references: `2 Timothy 3:16; Hebrews`
  },
  {
    id: identifier++,
    title: `Memorial`,
    content: `Understand the importance of the Memorial as Jehovah’s approved celebration.\n\n1. What event does the Memorial commemorate?\n\n2. On which Jewish date is the Memorial held?\n\n3. What did Jesus use to represent his body?\n\n4. What did the wine represent at the Memorial?\n\n5. Who instituted the Memorial?\n\n6. In what year did Jesus institute the Memorial?\n\n7. Who should partake of the Memorial emblems?\n\n8. What covenant did Jesus mention during the Memorial?\n\n9. How often should the Memorial be held?\n\n10. What did Jesus do before passing the bread?\n\n11. Who were present at the first Memorial?\n\n12. What does the Memorial remind us of?\n\n13. Where did Jesus hold the first Memorial?\n\n14. What did Jesus say about the wine?\n\n15. Why is the Memorial held after sundown?\n\n16. What does the Memorial help us appreciate?\n\n17. Who should attend the Memorial?\n\n18. What did Jesus do after the Memorial?\n\n19. What prayer did Jesus offer before his arrest?\n\n20. Why is the Memorial important for pure worship?`,
    answers: `1. Jesus’ death, 2. Nisan 14, 3. Unleavened bread, 4. Jesus’ blood, 5. Jesus, 6. 33 CE, 7. Those with a heavenly hope, 8. The new covenant, 9. Once a year, 10. Gave thanks, 11. The apostles, 12. Jesus’ sacrifice, 13. An upper room in Jerusalem, 14. It is his blood of the covenant, 15. To align with the Passover, 16. The ransom sacrifice, 17. Everyone, 18. Went to the Garden of Gethsemane, 19. Prayed for his disciples, 20. It honors Jesus’ sacrifice`,
    references: `Luke 22:19-20; 1 Corinthians 11:23-25`
  },
  {
    id: identifier++,
    title: `Christmas`,
    content: `Examine why Christmas is not part of pure worship to Jehovah.\n\n1. Does the Bible give the date of Jesus’ birth?\n\n2. What season were shepherds in the fields when Jesus was born?\n\n3. Why does this season make December 25 unlikely?\n\n4. What did the wise men bring to Jesus?\n\n5. How old was Jesus when the wise men visited?\n\n6. What pagan festival influenced Christmas?\n\n7. Which Roman emperor made Christmas a holiday?\n\n8. In what year did Christmas become a holiday?\n\n9. What does the Christmas tree originate from?\n\n10. Why did early Christians not celebrate Christmas?\n\n11. What does Jehovah say about mixing pagan customs?\n\n12. What did Jesus say about traditions of men?\n\n13. What holiday should Christians celebrate instead?\n\n14. What does the star on a Christmas tree symbolize?\n\n15. Who is often associated with Christmas gift-giving?\n\n16. What is the origin of Santa Claus?\n\n17. Why does Christmas promote materialism?\n\n18. What did Jesus teach about giving?\n\n19. How can we honor Jesus instead of celebrating Christmas?\n\n20. Why does Jehovah reject Christmas celebrations?`,
    answers: `1. No, 2. Likely autumn, 3. Shepherds would not be in fields in winter, 4. Gold, frankincense, and myrrh, 5. About two years old, 6. Saturnalia, 7. Constantine, 8. 336 CE, 9. Pagan tree worship, 10. It was not part of pure worship, 11. Do not learn the way of the nations, 12. They nullify the word of God, 13. The Memorial, 14. Pagan sun worship, 15. Saint Nicholas, 16. A 4th-century bishop, 17. Focus on gifts and commercialism, 18. Give without expecting in return, 19. Observe the Memorial, 20. It has pagan origins`,
    references: `Jeremiah 10:2-4; Matthew 15:6`
  },
  {
    id: identifier++,
    title: `Easter`,
    content: `Learn why Easter does not align with Jehovah’s standards for worship.\n\n1. Does the Bible mention Easter?\n\n2. What pagan goddess is associated with Easter?\n\n3. What do Easter eggs symbolize?\n\n4. What is the origin of the Easter bunny?\n\n5. What event does Easter claim to celebrate?\n\n6. What did Jesus command his followers to commemorate?\n\n7. Why is the date of Easter tied to the spring equinox?\n\n8. What council fixed the date of Easter?\n\n9. In what year did this council occur?\n\n10. What does Jehovah say about adopting pagan customs?\n\n11. What did the early Christians celebrate instead of Easter?\n\n12. What does the Bible say about Jesus’ resurrection?\n\n13. How many days was Jesus in the tomb?\n\n14. What day of the week was Jesus resurrected?\n\n15. Why do some celebrate Good Friday?\n\n16. What does the Bible say about traditions of men?\n\n17. What did Paul warn about in Colossians?\n\n18. Why does Easter promote false teachings?\n\n19. What should Christians focus on instead of Easter?\n\n20. How can we honor Jesus’ resurrection?`,
    answers: `1. No, 2. Eostre, 3. Fertility and new life, 4. Pagan fertility symbols, 5. Jesus’ resurrection, 6. His death (Memorial), 7. Pagan influence, 8. Council of Nicaea, 9. 325 CE, 10. Do not learn the way of the nations, 11. The Memorial, 12. He was raised on the third day, 13. Three days and three nights, 14. The first day of the week, 15. To mark Jesus’ death, 16. They nullify God’s word, 17. Being misled by philosophy, 18. It mixes paganism with Christianity, 19. The Memorial, 20. By preaching the good news`,
    references: `1 Corinthians 15:4; Colossians 2:8`
  },
  {
    id: identifier++,
    title: `Birthdays`,
    content: `Discover why birthdays are not part of pure worship to Jehovah.\n\n1. Does the Bible record any faithful servants celebrating birthdays?\n\n2. Whose birthday is mentioned in Genesis?\n\n3. What happened at Pharaoh’s birthday celebration?\n\n4. Whose birthday is mentioned in the Christian Greek Scriptures?\n\n5. What happened at Herod’s birthday celebration?\n\n6. What did Job’s children do that concerned him?\n\n7. What did Job do after his children’s celebrations?\n\n8. Why did early Christians not celebrate birthdays?\n\n9. What pagan practices are associated with birthdays?\n\n10. What does the blowing out of candles symbolize?\n\n11. Why do birthday celebrations often promote selfishness?\n\n12. What does Jehovah value more than self-exaltation?\n\n13. What did Jesus teach about humility?\n\n14. Why might birthday celebrations lead to bad associations?\n\n15. What does the Bible say about giving?\n\n16. How can we show love without celebrating birthdays?\n\n17. What celebration does Jehovah approve?\n\n18. What historical figure condemned birthday celebrations?\n\n19. Why do birthday parties often lead to excess?\n\n20. How can we honor Jehovah instead of celebrating birthdays?`,
    answers: `1. No, 2. Pharaoh, 3. The baker was executed, 4. Herod, 5. John the Baptist was beheaded, 6. Feasted on their “day”, 7. Offered sacrifices for them, 8. They were pagan in origin, 9. Magic and superstition, 10. Wishing on candles, 11. They focus on self, 12. Humility, 13. The greatest must be the least, 14. They may involve worldly customs, 15. Give without expecting in return, 16. Give gifts on any day, 17. The Memorial, 18. Origen, 19. Focus on feasting and drinking, 20. Worship Him daily`,
    references: `Genesis 40:20-22; Mark 6:21-28`
  },
  {
    id: identifier++,
    title: `God’s Name`,
    content: `Learn the importance of knowing and using Jehovah’s name in worship.\n\n1. What is God’s personal name?\n\n2. In which scripture does Jehovah first reveal His name?\n\n3. What does the name Jehovah mean?\n\n4. How many times does Jehovah’s name appear in the Hebrew Scriptures?\n\n5. Why was Jehovah’s name removed from many Bible translations?\n\n6. What did Jesus say about making God’s name known?\n\n7. How did Jesus use Jehovah’s name?\n\n8. What does the Bible say about those who know Jehovah’s name?\n\n9. Why is it important to use Jehovah’s name?\n\n10. What did Jehovah command about His name?\n\n11. Which prophet said Jehovah’s name would be called upon?\n\n12. What does calling on Jehovah’s name mean?\n\n13. How can we sanctify Jehovah’s name?\n\n14. What prayer includes a request about Jehovah’s name?\n\n15. What does the Bible say about Jehovah’s name in the last days?\n\n16. Who will Jehovah help in the last days?\n\n17. How did the early Christians view Jehovah’s name?\n\n18. What did Paul say about Jehovah’s name?\n\n19. Why does Satan not want us to use Jehovah’s name?\n\n20. How can we show love for Jehovah’s name?`,
    answers: `1. Jehovah, 2. Exodus 3:14, 3. He Causes to Become, 4. Nearly 7,000 times, 5. Due to superstition, 6. He made it known to his disciples, 7. Included it in his prayers, 8. They will be protected, 9. It draws us closer to Him, 10. Not to misuse it, 11. Joel, 12. Worshipping Him, 13. By living in harmony with it, 14. The Lord’s Prayer, 15. It will be declared, 16. Those calling on His name, 17. They used it in worship, 18. Every tongue should confess it, 19. To distance us from God, 20. Use it in prayer and preaching`,
    references: `Exodus 3:14; Joel 2:32; Matthew 6:9`
  },
  {
    id: identifier++,
    title: `Creation`,
    content: `Explore Jehovah’s creation and what it teaches us about Him.\n\n1. Who created the heavens and the earth?\n\n2. Over how many days did Jehovah create the earth?\n\n3. What did Jehovah create on the first day?\n\n4. What did Jehovah create on the second day?\n\n5. What did Jehovah create on the third day?\n\n6. What did Jehovah create on the fourth day?\n\n7. What did Jehovah create on the fifth day?\n\n8. What did Jehovah create on the sixth day?\n\n9. What did Jehovah say about His creation?\n\n10. Who was with Jehovah during creation?\n\n11. What role did Jesus play in creation?\n\n12. What does creation reveal about Jehovah?\n\n13. What does the Bible say about the stars?\n\n14. How does creation show Jehovah’s power?\n\n15. What scientific fact does the Bible confirm about the earth?\n\n16. Who did Jehovah create to care for the earth?\n\n17. What did Jehovah command Adam and Eve to do?\n\n18. How does creation help us worship Jehovah?\n\n19. What does Jehovah promise about the earth?\n\n20. Why should we care for Jehovah’s creation?`,
    answers: `1. Jehovah, 2. Six days, 3. Light, 4. The sky, 5. Dry land and vegetation, 6. Sun, moon, and stars, 7. Sea creatures and birds, 8. Land animals and humans, 9. It was very good, 10. Jesus, 11. He was the firstborn of creation, 12. His power and wisdom, 13. He calls them by name, 14. Through its vastness and complexity, 15. It hangs on nothing, 16. Adam and Eve, 17. Fill the earth and subdue it, 18. It draws us closer to Him, 19. It will stand forever, 20. It reflects our love for Him`,
    references: `Genesis 1; Isaiah 40:26`
  },
  {
    id: identifier++,
    title: `Prayer`,
    content: `Understand how prayer is a vital part of true worship to Jehovah.\n\n1. Who should we pray to?\n\n2. In whose name should we pray?\n\n3. What did Jesus teach about prayer?\n\n4. How often should we pray?\n\n5. What should we pray for first?\n\n6. What does Jehovah promise to those who pray?\n\n7. Why should we pray for our enemies?\n\n8. What example did Jesus set in prayer?\n\n9. Where did Jesus often pray?\n\n10. What did Jesus pray for in Gethsemane?\n\n11. Who prayed for wisdom to judge Israel?\n\n12. What did Hannah pray for?\n\n13. How did Jehovah answer Hannah’s prayer?\n\n14. What did Daniel do despite a decree against prayer?\n\n15. How did Jehovah protect Daniel after his prayers?\n\n16. What does the Bible say about the prayers of the righteous?\n\n17. Why should prayers not be repetitive?\n\n18. What attitude should we have when praying?\n\n19. How does prayer strengthen our relationship with Jehovah?\n\n20. What should we do if our prayers seem unanswered?`,
    answers: `1. Jehovah, 2. Jesus, 3. The model prayer, 4. Without ceasing, 5. God’s Kingdom, 6. He hears them, 7. To show love, 8. Prayed often and alone, 9. In solitary places, 10. For God’s will to be done, 11. Solomon, 12. A son, 13. Gave her Samuel, 14. Prayed three times a day, 15. Saved him from the lions, 16. They accomplish much, 17. God wants heartfelt words, 18. Humility, 19. It draws us closer to Him, 20. Keep praying and trust Jehovah`,
    references: `Matthew 6:9-13; 1 Thessalonians 5:17`
  },
  {
    id: identifier++,
    title: `Paradise`,
    content: `Discover Jehovah’s promise of a paradise earth for those who worship Him.\n\n1. What did Jehovah originally create for Adam and Eve?\n\n2. Why did Adam and Eve lose paradise?\n\n3. What did Jehovah promise after the Fall?\n\n4. Who will restore paradise?\n\n5. What does the Bible say about the earth’s future?\n\n6. Who will live in the paradise earth?\n\n7. What will be absent in paradise?\n\n8. What did Jesus promise the evildoer on the stake?\n\n9. What does Revelation say about paradise?\n\n10. What will happen to death in paradise?\n\n11. How will animals behave in paradise?\n\n12. What did Isaiah prophesy about the earth?\n\n13. Who will teach people in paradise?\n\n14. What will people eat in paradise?\n\n15. How will paradise fulfill Jehovah’s purpose?\n\n16. What does the Bible say about work in paradise?\n\n17. Why will there be no sickness in paradise?\n\n18. What will the resurrected ones do in paradise?\n\n19. How can we gain life in paradise?\n\n20. What does paradise show about Jehovah’s love?`,
    answers: `1. The Garden of Eden, 2. They disobeyed Jehovah, 3. A seed to crush the serpent, 4. Jesus, 5. It will be a paradise, 6. The meek, 7. Death, pain, and tears, 8. He would be with him in paradise, 9. No more death or pain, 10. It will be swallowed up, 11. They will be at peace, 12. It will be full of knowledge of Jehovah, 13. The faithful, 14. Fruits of the earth, 15. The earth will be filled with obedient humans, 16. People will build houses and plant vineyards, 17. Jehovah will heal all, 18. Learn about Jehovah, 19. By exercising faith, 20. He wants the best for us`,
    references: `Genesis 3:15; Revelation 21:4`
  },
  {
    id: identifier++,
    title: `Idolatry & Cross`,
    content: `Learn why idolatry and the cross are not part of true worship.\n\n1. What does Jehovah say about idolatry?\n\n2. What did the Israelites make at Mount Sinai?\n\n3. What happened to the golden calf?\n\n4. Who destroyed the altar of Baal in Israel?\n\n5. What did Gideon do to promote true worship?\n\n6. What does the Bible say about worshipping images?\n\n7. What pagan symbol is linked to the cross?\n\n8. Did Jesus die on a cross or a stake?\n\n9. What Greek word is used for Jesus’ execution instrument?\n\n10. What does “stauros” mean?\n\n11. Who introduced the cross into Christianity?\n\n12. In what year did the cross become a Christian symbol?\n\n13. Why is wearing a cross considered idolatry?\n\n14. What did Paul say about boasting in the cross?\n\n15. What does Jehovah want instead of image worship?\n\n16. Why did the early Christians not use the cross?\n\n17. What did Jesus say about worship?\n\n18. What does the Bible say about the fate of idolaters?\n\n19. How can we avoid idolatry today?\n\n20. Why does Jehovah hate idolatry?`,
    answers: `1. Do not make or worship idols, 2. A golden calf, 3. Moses destroyed it, 4. Gideon, 5. Tore down Baal’s altar, 6. It is detestable, 7. Sun worship, 8. A stake, 9. Stauros, 10. An upright stake, 11. Constantine, 12. 312 CE, 13. It is an image of worship, 14. He boasted in Jesus’ sacrifice, 15. Worship in spirit and truth, 16. It was pagan, 17. Worship in spirit and truth, 18. They will not inherit God’s Kingdom, 19. Worship only Jehovah, 20. It dishonors Him`,
    references: `Exodus 32; John 4:23-24`
  },
  {
    id: identifier++,
    title: `Trinity`,
    content: `Understand why the Trinity doctrine is not supported by the Bible.\n\n1. Does the Bible teach the Trinity?\n\n2. What does the Bible say about Jehovah’s position?\n\n3. How does Jesus describe his relationship with Jehovah?\n\n4. What did Jesus say about his knowledge compared to Jehovah?\n\n5. Who did Jesus pray to?\n\n6. What does the Bible say about the holy spirit?\n\n7. Is the holy spirit described as a person?\n\n8. What council established the Trinity doctrine?\n\n9. In what year was the Trinity doctrine formalized?\n\n10. What did early Christians believe about God?\n\n11. Why was the Trinity doctrine introduced?\n\n12. What does the Bible say about false teachings?\n\n13. What did Paul warn about in his letters?\n\n14. How does the Trinity obscure Jehovah’s identity?\n\n15. What did Jesus teach about true worship?\n\n16. Why is believing in the Trinity a form of false worship?\n\n17. What does Jehovah say about other gods?\n\n18. How can we worship Jehovah in truth?\n\n19. What does the Bible say about the oneness of God?\n\n20. Why does Satan promote the Trinity?`,
    answers: `1. No, 2. He alone is the Most High, 3. The Father is greater than he is, 4. He does not know the day or hour, 5. Jehovah, 6. It is God’s active force, 7. No, 8. Council of Nicaea, 9. 325 CE, 10. Jehovah is the only true God, 11. To blend pagan beliefs, 12. They lead to destruction, 13. False teachers, 14. It hides His name, 15. Worship in spirit and truth, 16. It misrepresents Jehovah, 17. There is no other, 18. Know the truth, 19. Jehovah is one, 20. To confuse people`,
    references: `John 14:28; Deuteronomy 6:4`
  },
  {
    id: identifier++,
    title: `Hellfire`,
    content: `Learn why the teaching of hellfire contradicts Jehovah’s justice.\n\n1. Does the Bible teach that the dead are tormented in hellfire?\n\n2. What does the Bible say about the condition of the dead?\n\n3. What is the Hebrew word for the grave?\n\n4. What does “Sheol” mean?\n\n5. What is the Greek word for the grave?\n\n6. What does “Hades” mean?\n\n7. What does the Bible say about the punishment for sin?\n\n8. What did Jesus say about the soul?\n\n9. Who introduced the idea of hellfire into Christianity?\n\n10. What pagan beliefs influenced the hellfire doctrine?\n\n11. What does Jehovah say about burning people?\n\n12. What did Jesus’ parable of the rich man and Lazarus mean?\n\n13. Why does the hellfire doctrine misrepresent Jehovah?\n\n14. What does the Bible say about Gehenna?\n\n15. What happened to things thrown into Gehenna?\n\n16. What does the Bible say about the fate of the wicked?\n\n17. Why does Satan promote the hellfire doctrine?\n\n18. What does Jehovah promise for the future?\n\n19. How can we trust Jehovah’s justice?\n\n20. What should we teach about the dead?`,
    answers: `1. No, 2. They are unconscious, 3. Sheol, 4. The common grave, 5. Hades, 6. The common grave, 7. Death, 8. It can be destroyed, 9. Early church leaders, 10. Greek and Roman mythology, 11. It never came into His heart, 12. A change in spiritual status, 13. It portrays Him as cruel, 14. A place of destruction, 15. They were burned up, 16. They will be destroyed, 17. To slander Jehovah, 18. Resurrection and paradise, 19. He is love, 20. They sleep in death`,
    references: `Ecclesiastes 9:5; Jeremiah 7:31`
  },
  {
    id: identifier++,
    title: `Immortality`,
    content: `Understand why the immortality of the soul is a false teaching.\n\n1. Does the Bible teach that the soul is immortal?\n\n2. What does the Bible say about the soul that sins?\n\n3. What did Jehovah tell Adam about death?\n\n4. What is the soul according to the Bible?\n\n5. Can the soul be destroyed?\n\n6. What does the Bible say about the dead?\n\n7. What pagan belief influenced the immortality doctrine?\n\n8. Who introduced the idea of an immortal soul into Christianity?\n\n9. What does the Bible say about the hope for the dead?\n\n10. What did Jesus say about the resurrection?\n\n11. Who has immortality according to the Bible?\n\n12. What does the Bible say about the body and spirit?\n\n13. Why does the immortality doctrine dishonor Jehovah?\n\n14. What did Paul say about the resurrection?\n\n15. What does the Bible say about the fate of the wicked?\n\n16. Why does Satan promote the immortality doctrine?\n\n17. What does Jehovah promise for the faithful?\n\n18. How can we gain everlasting life?\n\n19. What did Jesus teach about life?\n\n20. Why is the resurrection hope better than immortality?`,
    answers: `1. No, 2. It will die, 3. He would return to dust, 4. A living creature, 5. Yes, 6. They know nothing, 7. Greek philosophy, 8. Plato, 9. The resurrection, 10. They will rise, 11. Jehovah, 12. The spirit returns to God, 13. It denies the resurrection, 14. The dead will rise, 15. They will perish, 16. To deny the resurrection, 17. Everlasting life, 18. Through faith in Jesus, 19. He is the resurrection and the life, 20. It relies on Jehovah’s power`,
    references: `Ezekiel 18:4; John 11:25`
  },
  {
    id: identifier++,
    title: `Preserving Jehovah’s Word`,
    content: `Learn how Jehovah’s Word was preserved through ancient writings and translations.\n\n1. How many times does “YHWH” appear in the Hebrew Scriptures?\n\n2. Who wrote the Ten Commandments by Jehovah’s hand?\n\n3. What Greek translation retained “YHWH” in early copies?\n\n4. What uninspired texts did the Septuagint include?\n\n5. Which codex occasionally preserved “YHWH” in Hebrew script?\n\n6. What did Codex Vaticanus replace “YHWH” with?\n\n7. Who translated the Latin Vulgate?\n\n8. What did the Vulgate replace “YHWH” with?\n\n9. What discovery confirmed “YHWH” in the oldest writings?\n\n10. Which Dead Sea Scroll prominently uses “YHWH”?\n\n11. Who produced the first English Bible?\n\n12. What translation used “Jehovah” in Exodus 6:3?\n\n13. What spurious passage did the King James Version include?\n\n14. Which translation restored “Jehovah” in the Old Testament?\n\n15. What liberal rendering did the Revised Standard Version use for Isaiah 7:14?\n\n16. Which popular translation omitted “Jehovah” entirely?\n\n17. How many times does the New World Translation restore “Jehovah”?\n\n18. What uninspired passage does the NWT omit?\n\n19. Which ancient codices does the NWT rely on for the Christian Scriptures?\n\n20. How many languages is the NWT available in?`,
    answers: `1. 6,973, 2. Moses, 3. Septuagint, 4. Apocrypha, 5. Codex Sinaiticus, 6. Kyrios, 7. Jerome, 8. Dominus, 9. Dead Sea Scrolls, 10. Great Isaiah Scroll, 11. John Wycliffe, 12. Tyndale Bible, 13. 1 John 5:7, 14. American Standard Version, 15. Young woman, 16. New International Version, 17. 7,237, 18. Mark 16:9-20, 19. Sinaiticus and Vaticanus, 20. Over 200`,
    references: `Exodus 6:3; Isaiah 7:14`
  },
  {
    id: identifier++,
    title: `Unshakable Faith in Jehovah’s Kingdom`,
    content: `Explore how faithful ones maintain unshakable faith through trials, preparing for Jehovah’s Kingdom.\n\n1. What does Hebrews 12:28 say we are receiving?\n\n2. Who was martyred in 33 CE for his wisdom in preaching?\n\n3. In what year did Daniel face the lions’ den?\n\n4. Who faced ridicule while rebuilding Jerusalem’s walls?\n\n5. What did Noah endure as a preacher of righteousness?\n\n6. Whose brothers did not initially exercise faith in him?\n\n7. Who remained faithful despite family challenges in the 1st century?\n\n8. In what year did Joseph resist temptation in Egypt?\n\n9. Who endured loss around 1473 BCE, praising Jehovah?\n\n10. Who declared, “I’ve fought the fine fight,” in the 1st century?\n\n11. Who overcame doubt in 1107 BCE to lead Israel?\n\n12. Who was reassured by Jesus to become believing in 33 CE?\n\n13. In what year did Daniel’s companions refuse to bow to an image?\n\n14. Who showed courage to save her people in 475 BCE?\n\n15. Who sang praises in prison in 50 CE?\n\n16. In what year did Habakkuk rejoice despite hardship?\n\n17. Who proved his faith by offering up Isaac?\n\n18. What did Daniel do despite a prayer ban in 537 BCE?\n\n19. What prepares the faithful for the new earth?\n\n20. What command did Jesus give to make disciples?`,
    answers: `1. Unshakable Kingdom, 2. Stephen, 3. 537 BCE, 4. Nehemiah, 5. Mockery, 6. Jesus, 7. Timothy, 8. 1711 BCE, 9. Job, 10. Paul, 11. Gideon, 12. Thomas, 13. 607 BCE, 14. Esther, 15. Paul and Silas, 16. 607 BCE, 17. Abraham, 18. Kept praying, 19. Endurance, 20. Go, therefore, and make disciples`,
    references: `Hebrews 12:28; Matthew 28:19-20`
  },
  {
    id: identifier++,
    title: `Vindicating Jehovah’s Name`,
    content: `Discover how biblical truth and archaeological evidence uphold Jehovah’s sovereignty and name.\n\n1. What issue does Satan’s challenge in Eden raise?\n\n2. Who proved Satan’s accusation wrong by enduring suffering?\n\n3. In what year was Christ’s Kingdom established?\n\n4. What is the earliest extra-biblical evidence of “YHWH”?\n\n5. Who inscribed the Moabite Stone?\n\n6. What did the Moabite Stone mention capturing?\n\n7. What artifacts from c. 600 BCE bear blessings with “YHWH”?\n\n8. What phrase appears in the Lachish Letters invoking “YHWH”?\n\n9. Where were the Dead Sea Scrolls discovered?\n\n10. Which Dead Sea Scroll uses “YHWH” in Isaiah 42:8?\n\n11. What Septuagint fragment retains “YHWH” in Hebrew?\n\n12. Where is Papyrus Fouad 266 stored?\n\n13. Which codex occasionally preserves “YHWH” in Hebrew script?\n\n14. What uninspired texts did Codex Sinaiticus include?\n\n15. Which Masoretic codex is housed in the Israel Museum?\n\n16. How many times does the Leningrad Codex use “YHWH”?\n\n17. Who used “Jehovah” in his 1530 Pentateuch translation?\n\n18. What did Henry Ainsworth emphasize in his Psalms annotations?\n\n19. How many times does the New World Translation restore “Jehovah”?\n\n20. How many copies of the New World Translation have been printed?`,
    answers: `1. Universal sovereignty, 2. Job, 3. 1914, 4. Moabite Stone, 5. King Mesha, 6. Vessels of YHWH, 7. Silver Scrolls, 8. May YHWH cause my lord to hear tidings of peace, 9. Qumran caves, 10. Great Isaiah Scroll, 11. Papyrus Fouad 266, 12. Cairo Museum, 13. Codex Sinaiticus, 14. Apocrypha, 15. Aleppo Codex, 16. 6,973, 17. William Tyndale, 18. Jehovah’s name, 19. 7,237, 20. Over 240 million`,
    references: `Job 1:9-11; Isaiah 42:8`
  },
  {
    id: identifier++,
    title: `Restoring Pure Worship`,
    content: `Explore how faithful individuals battled apostasy to restore pure worship to Jehovah.\n\n1. Who stood firm against pagan festivals like Saturnalia?\n\n2. What did Polycarp declare before his martyrdom?\n\n3. Who opposed the Trinity doctrine at the Council of Nicaea?\n\n4. What unbiblical concept did Constantine promote?\n\n5. Who translated the Latin Vulgate, preserving scripture?\n\n6. What did Jerome replace “YHWH” with in the Vulgate?\n\n7. Who led the Waldensians to translate the Bible into vernacular languages?\n\n8. Where did the Waldensians hide their manuscripts?\n\n9. Who produced the first complete English Bible?\n\n10. What unscriptural practices did Jan Hus reject?\n\n11. Who used “Jehovah” in translating the Pentateuch?\n\n12. What false doctrines did Henry Grew reject?\n\n13. Who taught the hope of an earthly resurrection?\n\n14. Who founded the Watch Tower Society?\n\n15. What year did Charles Taze Russell predict for Christ’s enthronement?\n\n16. Who named the group Jehovah’s Witnesses?\n\n17. How many Supreme Court cases did Rutherford win?\n\n18. Who oversaw the release of the New World Translation?\n\n19. What school did Nathan H. Knorr found for missionaries?\n\n20. Approximately how many Jehovah’s Witnesses were active in 2024?`,
    answers: `1. Polycarp, 2. I am a Christian, 3. Arius, 4. The Trinity, 5. Jerome, 6. Dominus, 7. Peter Waldo, 8. The Alps, 9. John Wycliffe, 10. Indulgences, 11. William Tyndale, 12. Trinity and hellfire, 13. George Storrs, 14. Charles Taze Russell, 15. 1914, 16. Joseph Franklin Rutherford, 17. 43, 18. Nathan H. Knorr, 19. Gilead School, 20. 9 million`,
    references: `None`
  }
];

export default teachtruth;